name: Convert to PDF

on: 
  push:
  pull_request:
      branches: [master]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - name: Read ./config/header.yml
        id: header
        uses: juliangruber/read-file-action@v1
        with:
          path: ./config/header.yml
      - name: add page meta data
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<!--{META}-->"
          replace: ${{ steps.header.outputs.content }}
          include: "README.md"
      - uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<!--{ADDRESS}-->"
          replace: ${{ secrets.ADDRESS }}
          include: "README.md"
      - name: insert page breaks
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<!--{BREAK}-->"
          replace: "\\newpage"
          include: "README.md"
      - name: convert readme to pdf
        uses: docker://pandoc/latex:2.11.2
        with:
          args: --pdf-engine=lualatex --defaults ./config/profile.yml -H ./config/global.tex
      - uses: actions/upload-artifact@master
        with:
          name: alexandreJoyeux
          path: output
