name: Convert to PDF

on: 
  push:
  pull_request:
      branches: [master]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - name: add personal details
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<!--{ADDRESS}-->"
          replace: ${{ secrets.ADDRESS }}
          include: "README.md"
      - name: add personal details
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<!--{METADATA}-->"
          replace: ${{ secrets.METADATA }}
          include: "README.md"
      - name: convert readme to pdf
        uses: docker://pandoc/latex:2.11.2
        with:
          args: -s README.md --output=output/resume.pdf
      - uses: actions/upload-artifact@master
        with:
          name: alexandreJoyeux
          path: output
