name: Convert to PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
          echo "FILELIST=README.md" >> $GITHUB_ENV
      - uses: docker://auchida/pandoc:latest
        with:
          args: --pdf-engine=lualatex --output=output/resume.pdf README.md
      - uses: actions/upload-artifact@master
        with:
          name: resume.pdf
          path: output/resume.pdf
